### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by jvh1** [mach3/google-spreadsheet.php#1]
Hello, I have implemented your resources and blank page is appearing. here is the url: http://wecho256.com/2609_back/google/

I have downloaded "google/apiclient" package using composer.json file.

I have download the credentials.json and created the spreadsheet file on google drive and mentioned the file id on the code.

Please help me to solve the issue.

Regards.

**Comment by mach3** [comment]
Sorry to be so late.
I couldn't access that url now, I hope you have solved the problem already.

If not, would you inform as new issue, close this now.
